app:
  name: "weather-api"
  version: "1.0.0"
  env: "development"

server:
  port: "8080"
  read_timeout: 10
  write_timeout: 10
  idle_timeout: 120

weather:
  apis:
    - name: open-meteo
      timeout: 5
    - name: weatherapi
      api_key: "YOUR-API-KEY-HERE"
      timeout: 5

log:
  level: "info"
  format: "json"
