// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Weather API Support",
            "url": "https://github.com/your-username/weather-api",
            "email": "support@weatherapi.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/weather": {
            "get": {
                "description": "Retrieves weather forecast data for a specific location from multiple providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Weather"
                ],
                "summary": "Get weather forecast",
                "parameters": [
                    {
                        "maximum": 90,
                        "minimum": -90,
                        "type": "number",
                        "example": 40.7128,
                        "description": "Latitude coordinate (-90 to 90)",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 180,
                        "minimum": -180,
                        "type": "number",
                        "example": -74.006,
                        "description": "Longitude coordinate (-180 to 180)",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 14,
                        "minimum": 1,
                        "type": "integer",
                        "example": 3,
                        "description": "Number of forecast days (1-14, default: 5)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/http.WeatherResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Missing required parameter: lat"
                }
            }
        },
        "http.WeatherData": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2025-07-25"
                },
                "temp_max": {
                    "type": "number",
                    "example": 38
                },
                "temp_min": {
                    "type": "number",
                    "example": 24.3
                }
            }
        },
        "http.WeatherResponse": {
            "type": "object",
            "properties": {
                "forecast_window": {
                    "type": "integer",
                    "example": 5
                },
                "forecasts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/http.WeatherData"
                        }
                    }
                },
                "latitude": {
                    "type": "number",
                    "example": 40.7128
                },
                "longitude": {
                    "type": "number",
                    "example": -74.006
                }
            }
        }
    },
    "tags": [
        {
            "description": "Weather forecast operations",
            "name": "Weather"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Weather API",
	Description:      "A high-performance, multi-provider weather forecast API built with Go and Fiber.\nThis API aggregates weather data from multiple providers to provide reliable and comprehensive weather forecasts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
